cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'
tap 'caskroom/fonts'

brew 'ack'
brew 'awscli'
brew 'coreutils'
#brew 'flyway'
brew 'go'
# If have issues with the next step follow steps listed below.
# https://github.com/go-delve/homebrew-delve/issues/19
#brew 'go-delve/delve/delve'
brew 'grc'
brew 'jq'
brew 'openssl'
brew 'packer'
brew 'node'
brew 'readline'
brew 'puma/puma/puma-dev'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'terraform'
brew 'unrar'
brew 'wget'
brew 'yarn'

cask 'aerial'
cask 'alfred'
cask 'amazon-chime'
cask 'android-file-transfer'
cask 'atom'
cask 'chefdk'
cask 'docker'
cask 'docker-toolbox'
cask 'firefox'
cask 'font-fira-code'
cask 'google-chrome'
cask 'hipchat'
cask 'iterm2'
cask 'istat-menus'
cask 'java'
# cask 'microsoft-office'
cask 'paw'
cask 'postman'
cask 'rescuetime'
cask 'sequel-pro'
cask 'skype'
cask 'slack'
cask 'sourcetree'
cask 'transmit'
cask 'whatsapp'
cask 'vagrant'
cask 'virtualbox'
cask 'viscosity'
cask 'vlc'
cask 'zoomus'

# Installing from the Mac App Store via mas
# https://github.com/mas-cli/mas
mas "irvue", id: 1039633667
