cask_args appdir: '/Applications'

tap 'puma/puma'
tap 'aws/tap'
tap 'mas-cli/tap'


brew 'ack'
brew 'awscli'
brew 'aws-sam-cli'
brew 'coreutils'
brew 'git-flow'
brew 'go'
brew 'grc'
brew 'htop'
brew 'jq'
brew 'mas'
brew 'openssl'
brew 'packer'
brew 'nmap'
brew 'node'
brew 'nodenv'
brew 'nvm'
brew 'readline'
brew 'puma/puma/puma-dev'
brew 'pyenv'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'sqlite'
brew 'terraform'
brew 'unrar'
brew 'uv'
brew 'wget'
brew 'xz'
brew 'yarn'
brew 'zlib'

cask 'aerial'
cask 'amazon-chime'
cask 'amazon-workdocs'
cask 'amazon-workspaces'
cask 'docker'

cask 'firefox'
cask 'font-fira-code'
cask 'google-chrome'
cask 'kiro'
cask 'kiro-cli'
cask 'iterm2'
cask 'istat-menus'
cask 'temurin'
cask 'obsidian'
cask 'rapidapi'
cask 'pgadmin4'
cask 'postman'
cask 'raycast'
cask 'sequel-pro'
cask 'slack'
cask 'sourcetree'
cask 'transmit'
cask 'vagrant'
cask 'virtualbox'
cask 'viscosity'
cask 'visual-studio-code'
cask 'vlc'

# Installing from the Mac App Store via mas
# https://github.com/mas-cli/mas
mas "irvue", id: 1039633667
mas "Microsoft Remote Desktop 10", id: 1295203466